FROM python:3.6-stretch

ADD https://github.com/progrium/entrykit/releases/download/v0.4.0/entrykit_0.4.0_Linux_x86_64.tgz /entrykit.tgz
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /bin/wait-for-it

RUN tar xf /entrykit.tgz \
    && rm /entrykit.tgz \
    && mv ./entrykit /bin/entrykit \
    && chmod +x /bin/entrykit \
    && /bin/entrykit --symlink \
    && chmod +x /bin/wait-for-it

RUN pip install pipenv \
    && mkdir /code

WORKDIR /code

ENTRYPOINT ["prehook", "python -V", "--", \
            "prehook", "pipenv install", "--", \
            "wait-for-it", "db:5432", "-t", "0", "--", \
            "pipenv", "run", "flask", "run"]
