FROM python:3.6-stretch

ADD https://github.com/progrium/entrykit/releases/download/v0.4.0/entrykit_0.4.0_Linux_x86_64.tgz /entrykit.tgz

RUN tar xf /entrykit.tgz \
    && rm /entrykit.tgz \
    && mv ./entrykit /bin/entrykit \
    && chmod +x /bin/entrykit \
    && /bin/entrykit --symlink

RUN pip install pipenv \
    && mkdir /code

WORKDIR /code

ENTRYPOINT ["prehook", "python -V", "--", \
            "prehook", "pipenv install", "--", \
            "prehook", "pipenv run flask initdb", "--", \
            "prehook", "pipenv run flask generate", "--", \
            "pipenv", "run", "flask", "run"]
